# Prepossesing Step

In [1]:
import nltk
from nltk.stem.porter import PorterStemmer

In [2]:
import string

# 1.Word stemming

In [3]:
stemmer = PorterStemmer()
def stem_tokens(tokens,stemmer):
    stemmed = []
    for item in tokens:
        stemmed.append(stemmer.stem(item))
    return stemmed

# 2.Create tokens and remove punctuation by nltk

In [4]:
def tokenized(text):
    tokens = nltk.word_tokenize(text)
    tokens = [i for i in tokens if i not in string.punctuation]
    stems = stem_tokens(tokens,stemmer)
    return stems

# Read essay data by pandas

In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_excel('training_set_rel3.xls')
data.head()
df = data[data['essay_set']==1]
df.head()

essay_id  essay_set                                              essay  \
0         1          1  Dear local newspaper, I think effects computer...   
1         2          1  Dear @CAPS1 @CAPS2, I believe that using compu...   
2         3          1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...   
3         4          1  Dear Local Newspaper, @CAPS1 I have found that...   
4         5          1  Dear @LOCATION1, I know having computers has a...   

   rater1_domain1  rater2_domain1  rater3_domain1  domain1_score  \
0             4.0             4.0             NaN            8.0   
1             5.0             4.0             NaN            9.0   
2             4.0             3.0             NaN            7.0   
3             5.0             5.0             NaN           10.0   
4             4.0             4.0             NaN            8.0   

   rater1_domain2  rater2_domain2  domain2_score      ...        \
0             NaN             NaN            NaN      ...         
1             NaN             NaN            NaN      ...         
2             NaN             NaN            NaN      ...         
3             NaN             NaN            NaN      ...         
4             NaN             NaN            NaN      ...         

   rater2_trait3  rater2_trait4  rater2_trait5  rater2_trait6  rater3_trait1  \
0            NaN            NaN            NaN            NaN            NaN   
1            NaN            NaN            NaN            NaN            NaN   
2            NaN            NaN            NaN            NaN            NaN   
3            NaN            NaN            NaN            NaN            NaN   
4            NaN            NaN            NaN            NaN            NaN   

   rater3_trait2  rater3_trait3  rater3_trait4  rater3_trait5  rater3_trait6  
0            NaN            NaN            NaN            NaN            NaN  
1            NaN            NaN            NaN            NaN            NaN  
2            NaN            NaN            NaN            NaN            NaN  
3            NaN            NaN            NaN            NaN            NaN  
4            NaN            NaN            NaN            NaN            NaN  

[5 rows x 28 columns]

# Spliting data by cross validation for model validation

In [7]:
from sklearn.cross_validation import train_test_split

/home/saddam/ML/venv3/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [8]:
x1,x2,y1,y2 = train_test_split(df['essay'],df['domain1_score'],random_state=0,test_size=0.2)

# Create Tfidf table

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
tfidf = TfidfVectorizer(tokenizer=tokenized,stop_words='english',min_df=1).fit(x1)

In [11]:
X1 = tfidf.transform(x1)

In [12]:
X1

<1426x10222 sparse matrix of type '<class 'numpy.float64'>'
	with 144664 stored elements in Compressed Sparse Row format>

In [13]:
X2 = tfidf.transform(x2)

In [14]:
X2

<357x10222 sparse matrix of type '<class 'numpy.float64'>'
	with 35409 stored elements in Compressed Sparse Row format>

# Singular Value Decomposition(SVD) Practice

In [15]:
from scipy import linalg

In [16]:
import numpy as np

In [17]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            import pandas as pd

In [18]:
pd.DataFrame(X1.toarray(),columns=tfidf.get_feature_names()).head()

''  '.org   'a  'bloodi  'but  'comput  'con   'd  'do  'dog ...   \
0  0.000000    0.0  0.0      0.0   0.0      0.0   0.0  0.0  0.0   0.0 ...    
1  0.080777    0.0  0.0      0.0   0.0      0.0   0.0  0.0  0.0   0.0 ...    
2  0.000000    0.0  0.0      0.0   0.0      0.0   0.0  0.0  0.0   0.0 ...    
3  0.000000    0.0  0.0      0.0   0.0      0.0   0.0  0.0  0.0   0.0 ...    
4  0.000000    0.0  0.0      0.0   0.0      0.0   0.0  0.0  0.0   0.0 ...    

   zombi  zone  zoo  zoom   ~~    ‘         ’    “    ”    …  
0    0.0   0.0  0.0   0.0  0.0  0.0  0.000000  0.0  0.0  0.0  
1    0.0   0.0  0.0   0.0  0.0  0.0  0.000000  0.0  0.0  0.0  
2    0.0   0.0  0.0   0.0  0.0  0.0  0.000000  0.0  0.0  0.0  
3    0.0   0.0  0.0   0.0  0.0  0.0  0.144894  0.0  0.0  0.0  
4    0.0   0.0  0.0   0.0  0.0  0.0  0.000000  0.0  0.0  0.0  

[5 rows x 10222 columns]

In [19]:
a = X1.toarray()
a

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.0807774 ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.18528994,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.12266653],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
U , s, Vh = linalg.svd(a)

In [21]:
s

array([ 14.75722641,   5.06088288,   3.83582271, ...,   0.25261471,
         0.24970583,   0.23289428])

In [22]:
s.shape

(1426,)

In [23]:
print(s)

[ 14.75722641   5.06088288   3.83582271 ...,   0.25261471   0.24970583
   0.23289428]


In [24]:
i = 0
for k in s:
    if (k >= 0.80):
        i=i+1
print(i)

543


# SVM model create and fit 

In [25]:
from sklearn import svm

In [26]:
model = svm.SVC(decision_function_shape='ovo')

In [27]:
model.fit(X1,y1)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
predictions = model.predict(X2)

# Accuracy test

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score(y2,predictions)

0.40336134453781514

In [31]:
model.score(X2,y2)

0.40336134453781514

In [32]:
from sklearn.model_selection import cross_val_score


In [33]:
scores = cross_val_score(model,X2,y2,cv=5)

/home/saddam/ML/venv3/lib/python3.5/site-packages/sklearn/model_selection/_split.py:597: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


In [34]:
scores

array([ 0.39189189,  0.39189189,  0.40277778,  0.41428571,  0.41791045])