In [1]:
import numpy

In [2]:
from numpy import matrix
from numpy.random import rand

In [3]:
A = matrix(rand(4,4))

In [4]:
A

matrix([[ 0.46835993,  0.124102  ,  0.76759772,  0.51019593],
        [ 0.63313453,  0.39586628,  0.122607  ,  0.24776854],
        [ 0.86420596,  0.66950129,  0.8186792 ,  0.17764764],
        [ 0.53387176,  0.70932746,  0.1503266 ,  0.50838625]])

In [5]:
from numpy.linalg import svd

In [6]:
V, Sigma, Ustar = svd(A)

In [7]:
Sigma

array([ 2.00967612,  0.65509751,  0.41672977,  0.20674253])

In [8]:
Ustar = matrix(Ustar)

In [9]:
Ustar

matrix([[-0.63121461, -0.48571334, -0.50247115, -0.33641257],
        [ 0.15252666,  0.58709405, -0.79337197,  0.05115761],
        [-0.25031658, -0.19186436, -0.12948501,  0.94008686],
        [ 0.7180845 , -0.61853957, -0.31830376,  0.02112272]])

In [10]:
V = matrix(V)
V

matrix([[-0.4544243 , -0.66950826,  0.57396209,  0.12579654],
        [-0.36666616,  0.37304817, -0.04172612,  0.85126372],
        [-0.6676751 , -0.17639272, -0.68097121, -0.24366735],
        [-0.46180564,  0.61764016,  0.45288481, -0.44738298]])

# First two rows on Ustar

In [11]:
ustar = Ustar[:2]
ustar

matrix([[-0.63121461, -0.48571334, -0.50247115, -0.33641257],
        [ 0.15252666,  0.58709405, -0.79337197,  0.05115761]])

# First two column on V

In [12]:
V

matrix([[-0.4544243 , -0.66950826,  0.57396209,  0.12579654],
        [-0.36666616,  0.37304817, -0.04172612,  0.85126372],
        [-0.6676751 , -0.17639272, -0.68097121, -0.24366735],
        [-0.46180564,  0.61764016,  0.45288481, -0.44738298]])

In [13]:
v = V[:,:2]
v

matrix([[-0.4544243 , -0.66950826],
        [-0.36666616,  0.37304817],
        [-0.6676751 , -0.17639272],
        [-0.46180564,  0.61764016]])

# Create diagonale matrix from sigma

In [14]:
from numpy import diag

In [15]:
sigma = diag(Sigma[:2])
sigma

array([[ 2.00967612,  0.        ],
       [ 0.        ,  0.65509751]])

# Before singular value decomposition 

In [16]:
A

matrix([[ 0.46835993,  0.124102  ,  0.76759772,  0.51019593],
        [ 0.63313453,  0.39586628,  0.122607  ,  0.24776854],
        [ 0.86420596,  0.66950129,  0.8186792 ,  0.17764764],
        [ 0.53387176,  0.70932746,  0.1503266 ,  0.50838625]])

# After singular value decomposition the matrix is 

In [17]:
v*sigma*ustar

matrix([[ 0.50955685,  0.18608014,  0.80684714,  0.28478994],
        [ 0.50240447,  0.50138831,  0.17637449,  0.26039782],
        [ 0.82934539,  0.58389404,  0.76589882,  0.4454905 ],
        [ 0.64753201,  0.6883275 ,  0.14532348,  0.33291681]])

In [18]:
V.shape,Sigma.shape,Ustar.shape

((4, 4), (4,), (4, 4))

# Exersice

In [19]:
A = matrix(rand(3,3))

In [20]:
A

matrix([[ 0.99821167,  0.53015443,  0.75062339],
        [ 0.83599595,  0.13128303,  0.72761226],
        [ 0.16721344,  0.9931047 ,  0.02150112]])

In [21]:
U,s,V=svd(A)

In [22]:
s = diag(s)

In [23]:
s

array([[ 1.80632702,  0.        ,  0.        ],
       [ 0.        ,  0.91495953,  0.        ],
       [ 0.        ,  0.        ,  0.03436726]])

In [24]:
U*s*V

matrix([[ 0.99821167,  0.53015443,  0.75062339],
        [ 0.83599595,  0.13128303,  0.72761226],
        [ 0.16721344,  0.9931047 ,  0.02150112]])

In [25]:
B = matrix(rand(3,5))

In [26]:
B

matrix([[ 0.71118516,  0.68055994,  0.47395651,  0.24952392,  0.559278  ],
        [ 0.25591809,  0.49545639,  0.42520491,  0.83143182,  0.83740479],
        [ 0.90147998,  0.02786428,  0.99418708,  0.71874139,  0.25101442]])

In [27]:
u,s,v = svd(B,full_matrices=False)

In [28]:
u.shape,s.shape,v.shape

((3, 3), (3,), (3, 5))

In [29]:
s = diag(s)

In [30]:
u*s*v

matrix([[ 0.71118516,  0.68055994,  0.47395651,  0.24952392,  0.559278  ],
        [ 0.25591809,  0.49545639,  0.42520491,  0.83143182,  0.83740479],
        [ 0.90147998,  0.02786428,  0.99418708,  0.71874139,  0.25101442]])